judge-environment:
  run_mode: debug
  submission_path: /home/cu1/XOJ/submission
  resolution_path: /home/cu1/XOJ/resolutions

mysql:
  dsn: MySqlRoot:370802mysql@tcp(47.100.227.175:3306)/xoj_backend_dev?charset=utf8&parseTime=True&loc=Local
  default_string_size: 256
  disable_datetime_precision: true
  dont_support_rename_index: true
  dont_support_rename_column: true
  skip_initialize_with_version: false

rabbitmq:
  host: 47.100.227.175
  port: 5672
  username: fyj_xoj
  password: 123456

